export { default as settingsRouter } from './settingsRouter.js';
export { default as favoriteRouter } from './favoriteRouter.js';
export { default as wastedHistoryRouter } from './wastedHistoryRouter.js';
export { default as commentRouter } from './commentRouter.js';
export { default as movieRouter } from './movieRouter.js';
export { default as episodeRouter } from './episodeRouter.js';
export { default as seasonRouter } from './seasonRouter.js';
export { default as tvshowRouter } from './showRouter.js';
// export { default as gameRouter } from './gameRouter.js';
export { default as authRouter } from './authRouter.js';
export { default as userRouter } from './userRouter.js';
export { default as uploadRouter } from './uploadRouter.js';
