services:
  tmdb-movie:
    image: xthemey/tmdb
    container_name: tmdb-movie
    restart: always
    environment:
      - PORT=5050
      - DB_URL=mongodb://WastedTest:wastedTest1993@127.0.0.1:27017/WastedTest?authSource=admin&retryWrites=true&w=majority
      - DB_URL_TMDBMain=mongodb://XTheme:39911009XT@wasted-database:27017/wastedDB?authSource=admin&retryWrites=true&w=majority
      - DB_URL_TMDB=mongodb://XTheme:39911009XT@192.168.0.199:27017/wastedDB?authSource=admin&retryWrites=true&w=majority
      - DB_URL1=mongodb+srv://xthemey:3nY9Zt1993@wastedcluster.0yqs4zm.mongodb.net/WastedDB?retryWrites=true&w=majority
      - API_URL=http://192.168.0.199:5000
      - TMDB_API_KEY=9685b0e5d6b6cc91f12e186a1a7ba233
      - TMDB_API_URL=http://api.themoviedb.org/3
      - TMDB_IMG_URL=https://image.tmdb.org/t/p/original
      - TMDB_API_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5Njg1YjBlNWQ2YjZjYzkxZjEyZTE4NmExYTdiYTIzMyIsInN1YiI6IjU5ODc0YzViYzNhMzY4MzcxOTAxMDBkYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.e17FWz2m-XV_S8tyP-Rxl_999sYUEiG7nwOTeh5fkx0
      - RAWG_API_KEY=56dc624a6e2e49d1bd29144a5c1e7af7
      - RAWG_API_URL=https://api.rawg.io/api
      - IGDB_API_URL=https://api.igdb.com/v4
      - IGDB_CLIENT_TOKEN=0mst8imvxjfra1ek9k0ze21wqieoom
      - IGDB_CLIENT_ID=mru8pvdatjtsrc0r8d2d2g1s9xbplj
    depends_on:
      - wasted-database
    ports:
      - 5050:5050

  tmdb-show:
    image: xthemey/tmdb
    container_name: tmdb-show
    restart: always
    environment:
      - PORT=5030
      - DB_URL=mongodb://WastedTest:wastedTest1993@127.0.0.1:27017/WastedTest?authSource=admin&retryWrites=true&w=majority
      - DB_URL_TMDBMain=mongodb://XTheme:39911009XT@wasted-database:27017/wastedDB?authSource=admin&retryWrites=true&w=majority
      - DB_URL_TMDB=mongodb://XTheme:39911009XT@192.168.0.199:27017/wastedDB?authSource=admin&retryWrites=true&w=majority
      - DB_URL1=mongodb+srv://xthemey:3nY9Zt1993@wastedcluster.0yqs4zm.mongodb.net/WastedDB?retryWrites=true&w=majority
      - API_URL=http://192.168.0.199:5000
      - TMDB_API_KEY=9685b0e5d6b6cc91f12e186a1a7ba233
      - TMDB_API_URL=http://api.themoviedb.org/3
      - TMDB_IMG_URL=https://image.tmdb.org/t/p/original
      - TMDB_API_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5Njg1YjBlNWQ2YjZjYzkxZjEyZTE4NmExYTdiYTIzMyIsInN1YiI6IjU5ODc0YzViYzNhMzY4MzcxOTAxMDBkYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.e17FWz2m-XV_S8tyP-Rxl_999sYUEiG7nwOTeh5fkx0
      - RAWG_API_KEY=56dc624a6e2e49d1bd29144a5c1e7af7
      - RAWG_API_URL=https://api.rawg.io/api
      - IGDB_API_URL=https://api.igdb.com/v4
      - IGDB_CLIENT_TOKEN=0mst8imvxjfra1ek9k0ze21wqieoom
      - IGDB_CLIENT_ID=mru8pvdatjtsrc0r8d2d2g1s9xbplj
    depends_on:
      - wasted-database
    ports:
      - 5030:5030

  wasted-database:
    image: mongo:latest
    container_name: wasted-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: XTheme
      MONGO_INITDB_ROOT_PASSWORD: 39911009XT
      MONGO_INITDB_DATABASE: wastedDB
    volumes:
      - database:/data/db
    ports:
      - 27017:27017

volumes:
  database:
