export { default as authController } from './authController.js';
export { default as userController } from './userController.js';
export { default as movieController } from './movieController.js';
export { default as tvShowController } from './showController.js';
export { default as gameController } from './gameController.js';
export { default as searchController } from './searchController.js';
export { default as favoriteController } from './favoriteController.js';
export { default as wastedHistoryController } from './wastedHistoryController.js';
export { default as episodeController } from './episodeController.js';
